@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion

REM ============================================================
REM  Aivestor local deployment - configuration helper (Windows)
REM
REM  All output uses ASCII English to avoid CMD code-page issues.
REM  See INSTALL.md for the full Chinese guide.
REM ============================================================

cls
echo.
echo ==================================================
echo    Aivestor  local deployment  quick setup
echo ==================================================
echo.
echo This script writes a single file, .env.docker, in the
echo current folder. Nothing is uploaded anywhere.
echo.
echo Press Ctrl+C any time to abort.
echo --------------------------------------------------
echo.

REM Sanity check: PowerShell must be available (used to generate keys
REM and write UTF-8 file). Ships with Windows 10/11.
where powershell >nul 2>&1
if errorlevel 1 (
  echo [ERROR] PowerShell not found on PATH.
  echo         This script needs Windows PowerShell 5.1 or later,
  echo         which is bundled with Windows 10/11. Please run from
  echo         an ordinary cmd window.
  echo.
  pause
  exit /b 1
)

REM If .env.docker already exists, ask before overwriting.
if exist ".env.docker" (
  echo An existing .env.docker was detected.
  set /p overwrite="Overwrite it? (y/N): "
  if /i not "!overwrite!"=="y" (
    echo Aborted. Existing .env.docker kept as-is.
    echo.
    pause
    exit /b 0
  )
  echo.
)

REM ---------- Step 1: access URL ----------
echo [Step 1/2] Access URL
echo   Where will you open Aivestor in a browser?
echo     1) This machine only      ( http://localhost )         ^<-- recommended
echo     2) Other devices on LAN   ( http://192.168.x.x )
echo     3) Public server / domain ( http://1.2.3.4 or https://your.domain )
echo.
set /p addr_choice="  Choice (default 1): "
if "!addr_choice!"=="" set addr_choice=1

if "!addr_choice!"=="2" (
  echo.
  echo   Hint: run "ipconfig" in another cmd window to find your IPv4 address.
  set /p LAN_IP="  LAN IPv4 address: "
  if "!LAN_IP!"=="" (
    echo [ERROR] No IP entered. Aborting.
    pause
    exit /b 1
  )
  set NEXTAUTH_URL=http://!LAN_IP!
) else if "!addr_choice!"=="3" (
  echo.
  set /p NEXTAUTH_URL="  Full URL including http:// or https:// : "
  if "!NEXTAUTH_URL!"=="" (
    echo [ERROR] No URL entered. Aborting.
    pause
    exit /b 1
  )
) else (
  set NEXTAUTH_URL=http://localhost
)
echo   OK - access URL set to: !NEXTAUTH_URL!
echo.

REM ---------- Step 2: optional Bailian key ----------
echo [Step 2/2] Bailian embedding API key (optional)
echo   Used for the knowledge-base semantic search. Leave empty and
echo   Aivestor will fall back to keyword search. Other features are
echo   unaffected.
echo   Apply for a key at: https://bailian.console.aliyun.com/
echo.
set /p fill_bailian="  Enter a Bailian key now? (y/N): "
set BAILIAN_API_KEY=
if /i "!fill_bailian!"=="y" (
  set /p BAILIAN_API_KEY="  Paste API key: "
  echo   OK - key recorded.
) else (
  echo   Skipped. You can fill in BAILIAN_API_KEY inside .env.docker later
  echo   and re-run "docker compose up -d" to apply.
)
echo.

REM ---------- Generate secrets ----------
echo Generating cryptographic secrets...
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "-join ((48..57) + (65..90) + (97..122) | Get-Random -Count 20 | ForEach-Object {[char]$_})"`) do set DB_PASSWORD=%%i
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "$b = New-Object byte[] 32; [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b); [Convert]::ToBase64String($b)"`) do set NEXTAUTH_SECRET=%%i
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "$b = New-Object byte[] 32; [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b); ($b | ForEach-Object { $_.ToString('x2') }) -join ''"`) do set ENCRYPTION_KEY=%%i

if "!DB_PASSWORD!"=="" (
  echo [ERROR] Failed to generate DB_PASSWORD via PowerShell.
  echo         Open PowerShell manually and check it runs.
  pause
  exit /b 1
)
if "!NEXTAUTH_SECRET!"=="" (
  echo [ERROR] Failed to generate NEXTAUTH_SECRET via PowerShell.
  pause
  exit /b 1
)
if "!ENCRYPTION_KEY!"=="" (
  echo [ERROR] Failed to generate ENCRYPTION_KEY via PowerShell.
  pause
  exit /b 1
)

echo   OK - DB_PASSWORD       (20 chars)
echo   OK - NEXTAUTH_SECRET   (44 chars, base64)
echo   OK - ENCRYPTION_KEY    (64 chars, hex)
echo.

REM ---------- Write .env.docker as UTF-8 (no BOM) ----------
REM Use PowerShell so CMD redirection does not mangle bytes.
set _NEXTAUTH_URL=!NEXTAUTH_URL!
set _DB_PASSWORD=!DB_PASSWORD!
set _NEXTAUTH_SECRET=!NEXTAUTH_SECRET!
set _ENCRYPTION_KEY=!ENCRYPTION_KEY!
set _BAILIAN_API_KEY=!BAILIAN_API_KEY!

powershell -NoProfile -Command "$lines = @('# Aivestor local deployment configuration', '# Generated by setup.bat - keep this file private.', '', '# ---- Access URL ----', \"NEXTAUTH_URL=$env:_NEXTAUTH_URL\", '', '# ---- Auto-generated secrets (do not edit) ----', \"DB_PASSWORD=$env:_DB_PASSWORD\", \"NEXTAUTH_SECRET=$env:_NEXTAUTH_SECRET\", \"ENCRYPTION_KEY=$env:_ENCRYPTION_KEY\", '', '# ---- AI capabilities ----', '# Bailian embedding key (optional, leave empty for keyword search)', '# https://bailian.console.aliyun.com/', \"BAILIAN_API_KEY=$env:_BAILIAN_API_KEY\", '', '# Platform-paid DeepSeek key (optional, gives new users a free quota)', 'SYSTEM_DEEPSEEK_API_KEY=', '', '# ---- File storage (optional) ----', '# Leave empty to store files locally inside the Docker volume.', 'OSS_REGION=', 'OSS_ACCESS_KEY_ID=', 'OSS_ACCESS_KEY_SECRET=', 'OSS_BUCKET=', '', '# ---- Email (optional, used by forgot-password) ----', 'ALIYUN_ACCESS_KEY_ID=', 'ALIYUN_ACCESS_KEY_SECRET=', 'ALIYUN_EMAIL_FROM=', '', '# ---- SMS (optional, used by phone login) ----', 'ALIYUN_SMS_SIGN=', 'ALIYUN_SMS_TEMPLATE='); [IO.File]::WriteAllLines((Join-Path (Get-Location) '.env.docker'), $lines, (New-Object Text.UTF8Encoding $false))"

if errorlevel 1 (
  echo [ERROR] Failed to write .env.docker.
  echo         Make sure this folder is writable.
  pause
  exit /b 1
)

if not exist ".env.docker" (
  echo [ERROR] .env.docker was not created. Aborting.
  pause
  exit /b 1
)

set _NEXTAUTH_URL=
set _DB_PASSWORD=
set _NEXTAUTH_SECRET=
set _ENCRYPTION_KEY=
set _BAILIAN_API_KEY=

echo ==================================================
echo    Setup complete!
echo ==================================================
echo.
echo   Config written to:  %CD%\.env.docker
echo   Access URL:         !NEXTAUTH_URL!
echo.
echo Next step - start Aivestor with Docker:
echo.
echo   1. Make sure Docker Desktop is running.
echo   2. In this folder, run:
echo.
echo        docker compose --env-file .env.docker up -d --build
echo.
echo   First boot takes 3-10 minutes (image pull + build).
echo   When containers are up, open:  !NEXTAUTH_URL!
echo.
echo To change anything later, edit .env.docker in Notepad and
echo re-run the docker compose command above to apply.
echo.
echo See INSTALL.md for troubleshooting and admin commands.
echo.
pause
endlocal
